### ISSUE TITLE
Some questions about kernel code

### ISSUE THREAD

**Issue by JulyJohn** [dicecco1/fpga_caffe#10]
hi, @dicecco1 
Recently when I study your kernel code **[crp_layer_hwcn_cpfp.cpp](https://github.com/dicecco1/fpga_caffe/blob/master/src/fpga_caffe/layers/crp_layer_hwcn_cpfp.cpp)**, I am puzzled by some troubles.
First, how do you set the buffer size? according to what? For example, in 
https://github.com/dicecco1/fpga_caffe/blob/7a191704efd7873071cfef35772d7e7bf3e3cfd6/src/fpga_caffe/layers/crp_layer_hwcn_cpfp.cpp#L160 
inBuf[4][2 * 256 * 16], what does those numbers 4 2 256 16 means? And suppose my input blob shape size is 32 32 4 256, how can I associate it with the inBuf size number?

Second, what does the *Fact variable means? like 
https://github.com/dicecco1/fpga_caffe/blob/7a191704efd7873071cfef35772d7e7bf3e3cfd6/src/fpga_caffe/layers/crp_layer_hwcn_cpfp.cpp#L323
https://github.com/dicecco1/fpga_caffe/blob/7a191704efd7873071cfef35772d7e7bf3e3cfd6/src/fpga_caffe/layers/crp_layer_hwcn_cpfp.cpp#L324
and so on. and I find that you use the multiply of burstFact and imgFact to compute insize in 
https://github.com/dicecco1/fpga_caffe/blob/7a191704efd7873071cfef35772d7e7bf3e3cfd6/src/fpga_caffe/layers/crp_layer_hwcn_cpfp.cpp#L383

**Comment by dicecco1** [comment]
Buffer sizing:
The first number 4 corresponds to how many input channels are processed in parallel which is why that buffer is partitioned completely along the first dimension. 

The total number of elements that the buffer can fit is then 16 (because it's a vector of 16 cpfp values) * 4 * 2 * 256 * 16. Since the data is organized in HWCN order, the cpfp16 corresponds to how many input images are processed in parallel (so 16 in this case). The total buffer size is sized to try to improve the bandwidth utilization of the DDR by allowing for large enough bursts to take place, though there's still a mismatch between the DDR interface size and the port size here (512 bits vs 16*16 bits). 

In the case of 256 images, that leaves 256 / 16 (256 >> 4) images left to process. I guess the naming of imgFact and burstFact are kind of confusing in hindsight, imgFact and burstFact correspond to how many images are left to process and how many channels in a "channel burst" are left to process. 

Going back to your example, if the first layer is a 3x3 convolution, the kernel prefetches 3x3x4x256 inputs to compute the first window, then shifts the window to the left and only grabs the right most portion of the window so 3x1x4x256. Here the buffer is relatively under utilized because the first layer tends to have a small number of input channels.

**Comment by JulyJohn** [comment]
@dicecco1
 thanks, I think your answer helps me a lot. And more questions, what does icFact and wcFact mean in 
https://github.com/dicecco1/fpga_caffe/blob/7a191704efd7873071cfef35772d7e7bf3e3cfd6/src/fpga_caffe/layers/crp_layer_hwcn_cpfp_fw.cpp#L241-L244
