### ISSUE TITLE
Performance difference between Winograd algorithm and direct convolution

### ISSUE THREAD

**Issue by JulyJohn** [dicecco1/fpga_caffe#8]
In your [paper](http://ieeexplore.ieee.org/document/7929549/) related to this work, you mentioned a Winograd algorithm, but I can't find any information about it in this project, except one [file](https://github.com/dicecco1/fpga_caffe/blob/master/src/fpga_caffe/layers/wcrp_layer_hwcn_cpfp_fw.cpp), but it hasn't been used and it is denoted that only forward process is supported. 

So I was wondering how about the performance difference between Winograd and direct convolution ? Does it make sense that you deleted the things about Winograd due to Winograd doesn't perform better than direct convolution? And, could you unveil more details about the performance comparison?

**Comment by dicecco1** [comment]
Yeah so you can still access the original version from the paper if you go through the commit history, there's been a number of changes since then:

1. I switched from a 2D Winograd to 1D Winograd, this made the PEs less bloated and simplified the access pattern (don't need to access both along the width and height with this transform)
2. I changed the data layout from NCHW (this is the layout used in Caffe) to HWCN
3. CPFP support was added

My most recent work was focused mostly on training CNNs with CPFP so I spent a lot more time tuning the direct convolution engine to have good performance. The reason for this is that it's a lot harder to use the F(2,3) (or F(2x2,3x3)) Winograd convolution for the gradient w.r.t. the weights computation since the window size becomes as big as the input/output. 

The consequence of this is that the forward only implementation of direct convolution that's checked in right now is actually faster than the Winograd convolution, the average over several individual kernels has the Winograd convolution engine at around 300 GFLOP/s and forward only direct convolution at 325 GFLOP/s (peak is close to 400 GFLOP/s), if we include the backward paths as well then the direct convolution engine is closer to 300 GFLOP/s. 

Furthermore, the direct convolution engine is way more flexible than the Winograd engine:
- It has native support for other strides
- It can do essentially any kernel size (Winograd only supports 1x1, 3x3, and 5x5) with nearly the same performance across all kernel windows (1x1 goes a little lower since there's not much compute to be done)
- None of the padding enters into the computation which saves a lot of compute time for 3x3 and 5x5 kernels

You can still test different kernel configurations for the Winograd engine via the google tests, but I haven't added in the support directly to Caffe to run the Winograd engine because it requires a different weight layout.
